language: cpp

sudo: required


matrix:
  include:
    - compiler: clang
      os: osx
    - compiler: g++
      os: linux
      env: CMAKE_PREFER_SHARED_LIBRARIES=true
    - compiler: g++
      os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - binutils-dev
      - build-essential
      - cmake
      - gcc-5
      - g++-5
      - libcrypto++-dev
      - libpthread-stubs0-dev

before_install:
  - echo $LANG
  - echo $LC_ALL
  - export TYPTOP_NOUI=1
  - if [ $TRAVIS_OS_NAME == linux ]; then
       sudo apt-get install protobuf-compiler libprotobuf-dev libpam-dev;
       sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc; 
       sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; 
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew reinstall protobuf cmake; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo ./test/create_linux_user.sh tmptyptop hello_pass; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo ./test/create_mac_user.sh tmptyptop hello_pass; fi

before_script:
  - bash .build.sh

script:
  - TYPTOP_NOUI=1 ./build/test/tests -d yes --rng-seed 254
